---
- name: Install control-plane nodes
  hosts: control-plane
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    KUBERNETES_VERSION: v1.33
    CRIO_VERSION: v1.33
    POD_CIDR: "10.244.0.0/16"
    SERVICE_CIDR: "10.96.0.0/12"
    GO_VERSION: 1.25.6
    ETCD_VERSION: v3.4.37
  tasks:
    - name: Garantir diretório de keyrings
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: "0755"

    - name: Baixar chave GPG do repositório Kubernetes
      ansible.builtin.get_url:
        url: "https://pkgs.k8s.io/core:/stable:/{{ KUBERNETES_VERSION }}/deb/Release.key"
        dest: /tmp/kubernetes-release.key
        mode: "0644"

    - name: Converter chave GPG para formato dearmor
      ansible.builtin.command:
        cmd: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes-release.key
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Adicionar repositório APT do Kubernetes
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/kubernetes.list
        content: |
          deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/{{ KUBERNETES_VERSION }}/deb/ /
        mode: "0644"
    - name: Baixar chave GPG do repositório CRI-O
      ansible.builtin.get_url:
        url: "https://download.opensuse.org/repositories/isv:/cri-o:/stable:/{{ CRIO_VERSION }}/deb/Release.key"
        dest: /tmp/crio-release.key
        mode: "0644"
    - name: Converter chave GPG do CRI-O para formato dearmor
      ansible.builtin.command:
        cmd: gpg --dearmor -o /etc/apt/keyrings/crio-apt-keyring.gpg /tmp/crio-release.key
        creates: /etc/apt/keyrings/crio-apt-keyring.gpg
    - name: Adicionar repositório APT do CRI-O
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/crio.list
        content: |
          deb [signed-by=/etc/apt/keyrings/crio-apt-keyring.gpg] https://download.opensuse.org/repositories/isv:/cri-o:/stable:/{{ CRIO_VERSION }}/deb/ /
        mode: "0644"

    - name: Atualizar cache do APT
      ansible.builtin.apt:
        update_cache: true
    - name: Install kubeadm, kubelet and kubectl
      apt:
        name:
          - kubeadm
          - kubelet
          - kubectl
          - cri-o
        state: present
        update_cache: yes
