#SPDX-License-Identifier: MIT-0
---
# Variaveis Globais
observability_root: /monitoring
external_loki_url: http://192.168.200.41:3100
external_prometheus_url: http://192.168.200.41:9090

# Variaveis Grafana
grafana_version: "13.0"
grafana_host: "grafana"
grafana_port: 3000

#Variaveis Loki
loki_http_port: 3100
loki_grpc_port: 9096
loki_auth_enabled: false
loki_version: "3.7"
loki_host: "loki"

# Variaveis Prometheus
prometheus_version: "v3.14.0"
promeheus_host: "prometheus"
prometheus_port: 9090
# Variaveis Alertmanager
alertmanager_version: "v0.34.0"
alertmanager_host: "alertmanager"
alertmanager_port: 9093

# Variaveis telegram
telegram_api_url: "https://api.telegram.org"
