- name: Check if worker node is already joined to the cluster
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubeadm_init_check
- name: Debug kubeadm join check result
  ansible.builtin.debug:
    msg: " {{ ansible_hostname }} has joined: {{ kubeadm_init_check.stat.exists }}"
  when: worker_join | default(false) and kubeadm_init_check.stat.exists
- name: CMD | Join worker nodes to the cluster
  ansible.builtin.command: |
    {{ hostvars['control-plane-1'].kubeadm_join_command }}
  register: kubeadm_join_output
  when: worker_join | default(false) and not kubeadm_init_check.stat.exists
- name: Debug kubeadm join output
  ansible.builtin.debug:
    msg: "{{ hostvars['control-plane-1'].kubeadm_join_command }}"
  when: woker_join | default(false) and not kubeadm_init_check.stat.exists
