---
- name: "Create kubeadm join command for control nodes"
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  ansible.builtin.command: |
    kubeadm token create --print-join-command
  register: kubeadm_join_command
  changed_when: false
  when: control_plane_join_command | default(false)
- name: "debug kubeadm join command"
  ansible.builtin.debug:
    msg: "{{ kubeadm_join_command.stdout }}"
  when: control_plane_join_command | default(false)
- name: "Set kubeadm join command as fact"
  ansible.builtin.set_fact:
    kubeadm_join_command: "{{ kubeadm_join_command.stdout }}"
  when: control_plane_join_command | default(false)
...
