apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-wide-viewer
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "list"
      - "get"
      - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-wide-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-wide-viewer
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: cluster-wide-viewer
