#SPDX-License-Identifier: MIT-0
---
# vars file for kubeadm_init
control_plane_endpoint: "192.168.56.31:6443"
apiserver_cert_extra_sans:
  - "192.168.56.31"
  - "192.168.56.11"
  - "192.168.56.12"
  - "192.168.56.13"
...
