#SPDX-License-Identifier: MIT-0
---
# defaults file for kubeadm_init
pod_network_cidr: "10.244.0.0/16"
service_cidr: "10.96.0.0/12"
go_version: "1.25.6"
etcd_version: "v3.4.37"
#calico and tigera: https://docs.tigera.io/calico/latest/getting-started/kubernetes/quickstart
calico_version: "v3.32.0"
...
