all:
  children:
    kubernetes:
      children:
        control-plane:
          hosts:
            control-plane-1:
              ansible_host: 192.168.56.11
            control-plane-2:
              ansible_host: 192.168.56.12
            control-plane-3:
              ansible_host: 192.168.56.13
        join_control_plane_source:
          hosts:
            control-plane-1:

        join_control_plane_targets:
          hosts:
            control-plane-2:
            control-plane-3:

        workers:
          hosts:
            # worker-1:
            #   ansible_host: 192.168.56.21
            worker-2:
              ansible_host: 192.168.56.22

    load-balancer:
      hosts:
        ha-proxy-1:
          ansible_host: 192.168.56.31
